const GET_ALL_USERS = "user:GET_ALL_USERS"
const GET_ALL_ADMINS = "user:GET_ALL_ADMINS"
const DELETE_USER = "user:DELETE_USER"
const DELETE_ADMIN = "user:DELETE_ADMIN"
const UPDATE_USER = "user:UPDATE_USER"
const LOGOUT = "user:LOGOUT"

module.exports = {
    GET_ALL_USERS,
    GET_ALL_ADMINS,
    DELETE_USER,
    DELETE_ADMIN,
    UPDATE_USER,
    LOGOUT
}